//! Auto-generated `index.md` table of contents.
//!
//! `index.md` lives at the vault root and is regenerated on every ingest
//! (and via `scriptorium reindex`). It groups all wiki pages by their
//! primary type tag and alphabetizes within each group, producing a flat
//! browse-style index that complements link-graph navigation.
//!
//! The function is a pure projection of the page set, deliberately
//! deterministic — calling it twice on the same input produces identical
//! output (no timestamps, no random ordering). That's what makes the
//! "skip if unchanged" optimization in [`crate::ingest`] safe: ingest only
//! stages an `index.md` write when the rendered bytes differ from disk.

use std::fmt::Write;

use crate::vault::Page;

/// The controlled vocabulary of page-type tags. Order here is the order
/// sections appear in the rendered index. Pages whose first matching type
/// tag is in this list go into that bucket; pages with no recognized type
/// tag fall into "Other".
const TYPE_BUCKETS: &[(&str, &str)] = &[
    ("topic", "Topics"),
    ("concept", "Concepts"),
    ("pattern", "Patterns"),
    ("entity", "Entities"),
    ("playbook", "Playbooks"),
    ("reference", "References"),
    ("paper", "Papers"),
    ("talk", "Talks"),
    ("note", "Notes"),
];

/// Render `index.md` from a slice of pages. Pure, deterministic, testable.
#[must_use]
pub fn render(pages: &[Page]) -> String {
    let mut out = String::new();
    out.push_str("# Index\n\n");
    out.push_str("_Auto-generated by scriptorium. Do not edit by hand — changes are overwritten on the next ingest or reindex._\n\n");

    if pages.is_empty() {
        out.push_str("No pages yet. Run `scriptorium ingest <path>` to add a source and populate the wiki.\n");
        return out;
    }

    // Bucket each page by type tag, with TYPE_BUCKETS order taking precedence
    // over the page's own tag order. So a page tagged `["entity", "topic"]`
    // buckets under Topics (because `topic` appears earlier in TYPE_BUCKETS),
    // not under Entities. This makes bucketing deterministic regardless of
    // how the LLM happens to order the tags.
    let mut buckets: Vec<Vec<&Page>> = vec![Vec::new(); TYPE_BUCKETS.len()];
    let mut other: Vec<&Page> = Vec::new();
    for page in pages {
        let bucket_idx = TYPE_BUCKETS
            .iter()
            .position(|(t, _)| page.frontmatter.tags.iter().any(|tag| tag == t));
        match bucket_idx {
            Some(i) => buckets[i].push(page),
            None => other.push(page),
        }
    }

    // Sort each bucket by lowercased title for stable, case-insensitive order.
    // `sort_by_key` allocates once per element rather than once per comparison.
    for bucket in &mut buckets {
        bucket.sort_by_key(|p| p.frontmatter.title.to_lowercase());
    }
    other.sort_by_key(|p| p.frontmatter.title.to_lowercase());

    // Render each non-empty bucket as `## <Label> (<count>)` followed by a
    // bullet list of `[[stem|Title]]` wikilinks. `write!` against a `String`
    // is infallible, so the unwraps cannot panic.
    for (i, (_, label)) in TYPE_BUCKETS.iter().enumerate() {
        let pages_in_bucket = &buckets[i];
        if pages_in_bucket.is_empty() {
            continue;
        }
        writeln!(out, "## {} ({})\n", label, pages_in_bucket.len()).unwrap();
        for page in pages_in_bucket {
            let stem = page.path.file_stem().unwrap_or("");
            writeln!(out, "- [[{}|{}]]", stem, page.frontmatter.title).unwrap();
        }
        out.push('\n');
    }

    if !other.is_empty() {
        writeln!(out, "## Other ({})\n", other.len()).unwrap();
        for page in &other {
            let stem = page.path.file_stem().unwrap_or("");
            writeln!(out, "- [[{}|{}]]", stem, page.frontmatter.title).unwrap();
        }
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::vault::page::{Frontmatter, PageId};
    use camino::Utf8PathBuf;
    use chrono::{TimeZone, Utc};
    use std::collections::BTreeMap;

    fn fake_page(stem: &str, title: &str, tags: &[&str]) -> Page {
        let now = Utc.with_ymd_and_hms(2026, 4, 6, 12, 0, 0).unwrap();
        Page {
            path: Utf8PathBuf::from(format!("wiki/{stem}.md")),
            frontmatter: Frontmatter {
                id: PageId::new(),
                title: title.into(),
                created: now,
                updated: now,
                sources: vec![],
                tags: tags.iter().map(|s| (*s).to_string()).collect(),
                aliases: vec![],
                schema_version: 1,
                extra: BTreeMap::new(),
            },
            body: String::new(),
        }
    }

    #[test]
    fn empty_input_renders_empty_marker() {
        let out = render(&[]);
        assert!(out.contains("# Index"));
        assert!(out.contains("No pages yet"));
        assert!(!out.contains("##"));
    }

    #[test]
    fn single_entity_renders_in_entities_bucket() {
        let pages = vec![fake_page("foo", "Foo", &["entity"])];
        let out = render(&pages);
        assert!(out.contains("## Entities (1)"));
        assert!(out.contains("- [[foo|Foo]]"));
    }

    #[test]
    fn buckets_appear_in_declared_order_not_input_order() {
        // Inputs: a note, then a concept, then a topic. Output: topics first.
        let pages = vec![
            fake_page("alpha", "Alpha", &["note"]),
            fake_page("beta", "Beta", &["concept"]),
            fake_page("gamma", "Gamma", &["topic"]),
        ];
        let out = render(&pages);
        let topics = out.find("## Topics").unwrap();
        let concepts = out.find("## Concepts").unwrap();
        let notes = out.find("## Notes").unwrap();
        assert!(topics < concepts);
        assert!(concepts < notes);
    }

    #[test]
    fn within_bucket_sort_is_alphabetical_case_insensitive() {
        let pages = vec![
            fake_page("zebra", "zebra", &["entity"]),
            fake_page("apple", "Apple", &["entity"]),
            fake_page("banana", "BANANA", &["entity"]),
        ];
        let out = render(&pages);
        let apple = out.find("[[apple").unwrap();
        let banana = out.find("[[banana").unwrap();
        let zebra = out.find("[[zebra").unwrap();
        assert!(apple < banana);
        assert!(banana < zebra);
    }

    #[test]
    fn unknown_type_tag_falls_into_other_bucket() {
        let pages = vec![fake_page("foo", "Foo", &["weird"])];
        let out = render(&pages);
        assert!(out.contains("## Other (1)"));
    }

    #[test]
    fn no_type_tag_falls_into_other_bucket() {
        let pages = vec![fake_page("foo", "Foo", &["domain/llm"])];
        let out = render(&pages);
        assert!(out.contains("## Other (1)"));
    }

    #[test]
    fn first_matching_type_tag_wins() {
        // A page with both `topic` and `entity` should bucket as `topic`
        // (first in TYPE_BUCKETS order, regardless of tag list order).
        let pages = vec![fake_page("foo", "Foo", &["entity", "topic"])];
        let out = render(&pages);
        assert!(out.contains("## Topics (1)"));
        assert!(!out.contains("## Entities"));
    }

    #[test]
    fn render_is_deterministic() {
        let pages = vec![
            fake_page("bar", "Bar", &["entity"]),
            fake_page("foo", "Foo", &["concept"]),
        ];
        assert_eq!(render(&pages), render(&pages));
    }

    #[test]
    fn unicode_titles_sort_after_latin() {
        let pages = vec![
            fake_page("alpha", "Alpha", &["concept"]),
            fake_page("shchodennyk", "Щоденник", &["concept"]),
            fake_page("zebra", "Zebra", &["concept"]),
        ];
        let out = render(&pages);
        let alpha = out.find("[[alpha").unwrap();
        let zebra = out.find("[[zebra").unwrap();
        let shch = out.find("[[shchodennyk").unwrap();
        // Latin letters come before Cyrillic in lowercase code-point order.
        assert!(alpha < zebra);
        assert!(zebra < shch);
    }
}
